# Generated by Django 5.0.4 on 2024-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость(рубли)'),
        ),
    ]
