# Generated by Django 5.0.4 on 2024-04-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usertype', verbose_name='Вид деятельности '),
        ),
    ]
